In [13]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [15]:
import numpy as np
x = [1,2,3,4]
y = np.array(x)
y

array([1, 2, 3, 4])

In [16]:
l = []
for i in range(1,5):
    x = int(input("Enter the numbers of your choice:"))
    l.append(x)
print(np.array(l))


Enter the numbers of your choice: 1
Enter the numbers of your choice: 2
Enter the numbers of your choice: 3
Enter the numbers of your choice: 4


[1 2 3 4]


In [21]:
x = np.array([[1,2,3,4],[1,2,3,4]])
print(x)
print(x.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [23]:
l = [[1,2,3,4],[5,6,7,8]]
x = np.array(l)
print(x)
print(x.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [25]:
import numpy as np
x = np.array([1,2,3,4])
print(x)


[1 2 3 4]


In [1]:
import numpy as np
l = [[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]
x = np.array(l)
print(x)
print(x.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [7]:
 import numpy as np
arr_zeros = np.zeros(4)
arr_zeros1 = np.zeros((3,4))
print(arr_zeros)
print()
print(arr_zeros1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
import numpy as np
arr_ones = np.ones(3)
arr_ones1 = np.ones((3,4))
print(arr_ones)
print()
print(arr_ones1)

[1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
import numpy as np
arr_empty = np.empty((3,0))
print(arr_empty)
print(arr_empty.ndim)

[]
2


In [ ]:
#Range
import numpy as np
ar_rn = np.arange(4)
print(ar_rn)

In [36]:
import numpy as np
ar_rn = np.arange(3,4)
print(ar_rn)
print(ar_rn.ndim)

[3]
1


In [40]:
#diagonal
arr_diag = np.eye(3)
print(arr_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
arr_diag = np.eye(3,5)
print(arr_diag)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [44]:
#linespace
arr_lin = np.linspace(0,20, num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]


In [46]:
#random
#rand() is used to generate random numbers between 0 and 1
import numpy as np
var = np.random.rand(4)
print(var)

[0.57270838 0.9625957  0.3693309  0.153144  ]


In [48]:
var1 = np.random.rand(3,5)
print(var1)

[[0.58862858 0.4792956  0.30250775 0.63258941 0.503951  ]
 [0.47443286 0.22750529 0.10247287 0.60556324 0.42412268]
 [0.61424845 0.32139666 0.8287065  0.53927543 0.29149788]]


In [52]:
#randn() is used to generate nos closed to zero may generate negative aswell
import numpy as np
var = np.random.randn(4)
print(var)

[-0.03060124 -0.08982139  0.18637958 -0.73256828]


In [54]:
import numpy as np
var = np.random.randn(3,5)
print(var)

[[ 0.43579579  0.65694472 -0.78500497  1.2322277   0.11980766]
 [ 0.47960962  1.46665053 -2.05647484  1.14083274  0.13633831]
 [ 0.52299735 -0.04658825 -0.24444016 -1.55467419 -1.9031218 ]]


In [56]:
#ranf gives nos starting from 0.0 but less than 1.0 doesnt include 1
import numpy as np
var = np.random.ranf(4)
print(var)

[0.70033364 0.61405121 0.51236042 0.39668013]


In [72]:
#randint 
#randint(min,max,total_value)
import numpy as np
var = np.random.randint(4,20,5)
print(var)

[15 15  9  4  8]


In [74]:
#data_types
import numpy as np
var = np.array([1,2,3,4,5,6,7,12,13,14,15,16])
print("Data Type:", var.dtype)

Data Type: int32


In [77]:
import numpy as np
var = np.array([1.2,2.3,4.5,6.6])
print("Data Type:", var.dtype)

Data Type: float64


In [79]:
import numpy as np
var = np.array(["m","t"])
print("Data Type:", var.dtype)


Data Type: <U1


In [81]:
import numpy as np
var = np.array([1,2,3,4,5,6,7,12,13,14,15,16,"t","m"])
print("Data Type:", var.dtype)

Data Type: <U11


In [87]:
import numpy as np
var = np.array([1,2,3,4],dtype = np.int8)
print(var)
print(var.dtype)

[1 2 3 4]
int8


In [91]:
import numpy as np
x = np.array([1,2,3,4],dtype = "f")
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float32


In [97]:
import numpy as np
x1 = np.array([1,2,3,4])
new = np.float32(x1)
print(x1)
print(new)
print(x1.dtype)
print(new.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
int32
float32


In [99]:
import numpy as np
x1 = np.array([1,2,3,4])
new = np.float32(x1)
new1 = np.int_(new)
print(x1)
print(new)
print(new1)
print(x1.dtype)
print(new.dtype)
print(new1.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]
int32
float32
int32


In [101]:
x3 = np.array([1,2,3,4])
neww = x3.astype(float)
print(x3)
print(neww)

[1 2 3 4]
[1. 2. 3. 4.]


In [1]:
import numpy as np
var = np.array([1,2,3,4])
var_add = var + 3
print(var_add)

[4 5 6 7]


In [3]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = var1 + var2
print(var_add)

[2 4 6 8]


In [7]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = np.add(var1,var2)
print(var_add)

[2 4 6 8]


In [5]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_sub = var1 - var2
print(var_sub)

[0 0 0 0]


In [11]:
import numpy as np
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
var_add = var1 + var2
print(var1)
print()
print(var2)
print()
print(var_add)


[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [15]:
import numpy as np
var = np.array([1,2,3,4])
var_recp = np.reciprocal(var)
print(var_recp)

[1 0 0 0]


In [21]:
import numpy as np
var = np.array([1,2,3,4,5])
print("min:-",np.min(var),np.argmin(var))
print("max:-",np.max(var), np.argmax(var))
print("sqrt:-",np.sqrt(var))
print("sin:-",np.sin(var))
print("cos:-",np.cos(var))
print("cumsum:-", np.cumsum(var))

min:- 1 0
max:- 5 4
sqrt:- [1.         1.41421356 1.73205081 2.         2.23606798]
sin:- [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos:- [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
cumsum:- [ 1  3  6 10 15]


In [15]:
import numpy as np
var1 = np.array([[2,1,3],[9,8,7]])
print("min:-",np.min(var1, axis = 1))
print("max:-",np.max(var1, axis = 0))

min:- [1 7]
max:- [9 8 7]


In [25]:
import numpy as np
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [27]:
import numpy as np
var1 = np.array([1,2,3,4], ndmin=4)
print(var1)
print()
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)


In [33]:
#reshape
import numpy as np
var = np.array([1,2,3,4,5,6])
print(var)
print(var.ndim)

print()

x = var.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [35]:
#reshape
import numpy as np
var1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var1)
print(var1.ndim)

print()

x1 = var1.reshape(2,3,2)
print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [37]:
#reshape
import numpy as np
var1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var1)
print(var1.ndim)

print()

x1 = var1.reshape(2,3,2)
print(x1)
print(x1.ndim)

print()
one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [43]:
 import numpy as numpy
var1 = np.array([1,2,3,4])
print(var1)
print()
print(var1.shape)
 print()

var2 = np.array([[1],[2],[3],[4]])
print(var2)
print()
print(var2.shape)
print()
print(var1 + var2)

[1 2 3 4]

(4,)

[[1]
 [2]
 [3]
 [4]]

(4, 1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [45]:
import numpy as np
x = np.array([[1],[2]])
print(x)
print()
print(x.shape)
print()

y = np.array([[1,2,3],[4,5,6]])
print(y)
print()
print(y.shape)
print()
print(x+y)

[[1]
 [2]]

(2, 1)

[[1 2 3]
 [4 5 6]]

(2, 3)

[[2 3 4]
 [6 7 8]]


In [51]:
#indexing
import numpy as np
var = np.array([1,2,3,4])
print(var[1])
print(var[-4])


2
1


In [55]:
import numpy as np
var = np.array([[9,8,7],[6,5,4]])
print(var)
print()
print(var.ndim)
print()
print(var[0,2])
print(var[1,2])


[[9 8 7]
 [6 5 4]]

2

7
4


In [57]:
import numpy as np
var = np.array([[[1,2],[6,7]]])
print(var)
print()
print(var.ndim)
print()
print(var[0,1,1])

[[[1 2]
  [6 7]]]

3

7


In [75]:
#slicing
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9])
#               0,1,2,3,4,5,6,7,8
print(var)
print()
print("2 to 6:",var[1:6])
print("2 to 6:",var[1:6:2])
print("2 to end:",var[1:])
print("start to 6:",var[:6])
print("start to end:",var[:])
print("start to end:",var[::2])










[1 2 3 4 5 6 7 8 9]

2 to 6: [2 3 4 5 6]
2 to 6: [2 4 6]
2 to end: [2 3 4 5 6 7 8 9]
start to 6: [1 2 3 4 5 6]
start to end: [1 2 3 4 5 6 7 8 9]
start to end: [1 3 5 7 9]


In [81]:
import numpy as np
var = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(var)
print()
print(var[1,1:])
print(var[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[ 7  8  9 10]
[7 8 9]


In [1]:
import numpy as np
var = np.array([1,2,3,4,5])
print(var)
print()
for i in var:
    print(i)

[1 2 3 4 5]

1
2
3
4
5


In [5]:
import numpy as np
var1 = np.array([[1,2,3,4],[5,6,7,8]])
print(var1)
print()
for i in var1:
    print(var1)
print()
for i in var1:
    for k in i:
        print(k)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]

1
2
3
4
5
6
7
8


In [7]:
import numpy as np
var3 = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var3)
print()
print(var3.ndim)
print()
for i in var3:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [5 6 7 8]]]

3

1
2
3
4
5
6
7
8


In [9]:
import numpy as np
var3 = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var3)
print()
print(var3.ndim)
print()
for i in np.nditer(var3):
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]

3

1
2
3
4
5
6
7
8


In [13]:
import numpy as np
var3 = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var3)
print()
print(var3.ndim)
print()
for i,d in np.ndenumerate(var3):
    print(i,d)

[[[1 2 3 4]
  [5 6 7 8]]]

3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8


In [23]:
# COPY vs VIEW
import numpy as np
x = np.array([1,2,3,4])
co = x.copy()
x[1]=40
print("x:-",x)
print()
print("copy:-",co)

x:- [ 1 40  3  4]

copy:- [1 2 3 4]


In [25]:
import numpy as np
y = np.array([1,2,3,4])
vi = y.view()
y[1]=34
print("y:-",y)
print("view:-",vi)


y:- [ 1 34  3  4]
view:- [ 1 34  3  4]


In [3]:
#joining
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])
var_new = np.concatenate((var,var1))
print(var_new)

[1 2 3 4 5 6 7 8]


In [30]:
import numpy as np
var = np.array([[1,2,3],[4,5,6]])
var1 = np.array([[5,6,7],[8,9,10]])
print(var)
print()
print(var1)
print()
var_new = np.concatenate((var,var1),axis = 0)
print(var_new)

[[1 2 3]
 [4 5 6]]

[[ 5  6  7]
 [ 8  9 10]]

[[ 1  2  3]
 [ 4  5  6]
 [ 5  6  7]
 [ 8  9 10]]


In [34]:
import numpy as np
var = np.array([1,2,4,5])
var1 = np.array([5,6,8,9])
print(var)
print()
print(var1)
print()
var_new = np.stack((var,var1),axis = 0)
var_new1 = np.stack((var,var1),axis = 1)
var_new2 = np.hstack((var,var1))  #row
var_new3 = np.vstack((var,var1))  #column
var_new4 = np.dstack((var,var1))  #height


print(var_new)
print()
print(var_new1)
print()
print(var_new2)
print()
print(var_new3)
print()
print(var_new4)


[1 2 4 5]

[5 6 8 9]

[[1 2 4 5]
 [5 6 8 9]]

[[1 5]
 [2 6]
 [4 8]
 [5 9]]

[1 2 4 5 5 6 8 9]

[[1 2 4 5]
 [5 6 8 9]]

[[[1 5]
  [2 6]
  [4 8]
  [5 9]]]


In [42]:
#splitting
import numpy as np
var = np.array([1,2,3,4,5,6])
print(var)
print()
var_new = np.array_split(var,3)
print(var_new)
print(type(var_new))

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>


In [54]:
#splitting
import numpy as np
var = np.array([[1,2],[4,5],[8,9]])
print(var)
print()
var_new = np.array_split(var,3)
var_new1 = np.array_split(var,3,axis = 1)

print(var_new)
print()
print(var_new1)

print(type(var_new))

[[1 2]
 [4 5]
 [8 9]]

[array([[1, 2]]), array([[4, 5]]), array([[8, 9]])]

[array([[1],
       [4],
       [8]]), array([[2],
       [5],
       [9]]), array([], shape=(3, 0), dtype=int32)]
<class 'list'>


In [7]:
#where condition
import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9])
x = np.where((var == 2))
y = np.where((var%2)==0)
print(x)
print(y)



(array([1], dtype=int64),)
(array([1, 3, 5, 7], dtype=int64),)


In [17]:
#search sorted
import numpy as np
var = np.array([1,2,3,4,5,6])
x = np.searchsorted(var,[5])
y = np.searchsorted(var,[5],side="right")
z = np.searchsorted(var,[5],side="left")
z1 = np.searchsorted(var,[5,6,7],side="left")


print(x)
print(y)
print(z)
print(z1)



[4]
[5]
[4]
[4 5 6]


In [19]:
import numpy as np
var = np.array([1,4,2,3,5,7,8,6,9])
x = np.sort(var)
print(x)

[1 2 3 4 5 6 7 8 9]


In [21]:
import numpy as np
var = np.array(['v','z','y','x'])
x = np.sort(var)
print(x)

['v' 'x' 'y' 'z']


In [23]:
#sort
import numpy as np
var = np.array([[2,1,3],[5,7,6],[9,10,8]])
x = np.sort(var)
print(x)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]


In [29]:
#filter array
import numpy as np
var = np.array(['m','o','p','t'])
f = [True, False, False, True]
var1 = var[f]
print(var1)
print(type(var1))

['m' 't']
<class 'numpy.ndarray'>


In [31]:
#shuffle
import numpy as np
var = np.array([1,3,4,2,5])
np.random.shuffle(var)
print(var)


[1 4 2 3 5]


In [39]:
#unique
import numpy as np
var = np.array([1,2,2,2,3,4,5,6,7,8,8,8,8,8,9,9,9,9,9])
x = np.unique(var, return_index=True, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0,  1,  4,  5,  6,  7,  8,  9, 14], dtype=int64), array([1, 3, 1, 1, 1, 1, 1, 5, 5], dtype=int64))


In [45]:
#resize
import numpy as np
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(3,2))
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [65]:
#flatten and ravel
import numpy as np
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(3,2))
print(x)
print()
print("flatten:-", x.flatten(order="F"))
print()
print("ravel:-",np.ravel(x,order="k"))

[[1 2]
 [3 4]
 [5 6]]

flatten:- [1 3 5 2 4 6]

ravel:- [1 2 3 4 5 6]


In [85]:
#insert and append
import numpy as np
var = np.array([1,2,3,4,5,6])
v = np.insert(var,2,7)
w = np.append(var,2.5)
print(v)
print()
print(w)


[1 2 7 3 4 5 6]

[1.  2.  3.  4.  5.  6.  2.5]


In [93]:
import numpy as np
var = np.array([[1,2,3],[1,2,3]])
v = np.insert(var,2,3, axis = 0)
w = np.insert(var,2,3, axis = 1)
x = np.append(var,[[23,34,56]],axis=0)

print(v)
print()
print(w)
print()
print(x)

[[1 2 3]
 [1 2 3]
 [3 3 3]]

[[1 2 3 3]
 [1 2 3 3]]

[[ 1  2  3]
 [ 1  2  3]
 [23 34 56]]


In [95]:
#delete
import numpy as np
var = np.array([1,2,3,4,5])
v = np.delete(var,3)
print(v)


[1 2 3 5]


In [9]:
#matrix
import numpy as np
var = np.matrix([[1,2],[4,5]])
var1 = np.matrix([[1,2],[4,5]])
print(var)
print()
print(var+var1)
print()
print(var.dot(var1))
print(type(var))

[[1 2]
 [4 5]]

[[ 2  4]
 [ 8 10]]

[[ 9 12]
 [24 33]]
<class 'numpy.matrix'>


In [19]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [23]:
import numpy as np
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.swapaxes(var,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [27]:
import numpy as np
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.inv(var))


[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [38]:
import numpy as np
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.matrix_power(var,2))
print()
print(np.linalg.matrix_power(var,0))
print()
print(np.linalg.matrix_power(var,-2))


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [40]:
import numpy as np
var = np.matrix([[1,2],[3,4]])
print(var)
print()
print(np.linalg.det(var))

[[1 2]
 [3 4]]

-2.0000000000000004


In [42]:
import numpy as np
var = np.matrix([[1,2,3],[3,4,5],[6,7,8]])
print(var)
print()
print(np.linalg.det(var))

[[1 2 3]
 [3 4 5]
 [6 7 8]]

-3.7007434154172e-17
